# Setup
title:               jihyun
tagline:             'nice and slow'
description:         'janie_log'
url:                 http://jihyun-bit.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jihyun
  url:               https://github.com/jihyun-bit
  email:             ljh3623266@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
